#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro package install goclone <args...>"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  export PATH=$HOME/.go/bin:/usr/local/go/bin:/usr/local/bin:$PATH

  which goclone >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    # go installed
    which go >>/dev/null 2>&1
    if [ "$?" = "0" ]; then
      go install github.com/imthaghost/goclone/cmd/goclone@latest
      return
    fi

    if [ "$(os::is_macos)" = "true" ]; then
      pm install -y goclone
    else
      cd $ZMICRO_PLUGINS_PATH/package/packages/goclone
      log::error "not support in current system, please create an issue to $(git::issue_url)"
      exit 1
    fi
  fi

  log::success "install goclone success."
}

run() {
  core $@
}

run $@
